# Generated by Django 4.1.3 on 2022-12-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_job_limit_time_to_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="id_test",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
