# Generated by Django 4.1.2 on 2022-11-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_alter_company_user"),
        ("job", "0003_job_expected_result_test_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcategory",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="companies.company",
            ),
        ),
    ]
