# Generated by Django 4.1.2 on 2022-11-22 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "seekers_profile",
            },
        ),
        migrations.CreateModel(
            name="SkillInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=255)),
                ("skill_level", models.CharField(max_length=255)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_information",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "skills_information",
            },
        ),
        migrations.CreateModel(
            name="ExpirenceInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_current_job", models.BooleanField(default=False)),
                ("job_title", models.CharField(max_length=255)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "job_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expirences_information",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "expirences_information",
                "ordering": ["end_date"],
            },
        ),
        migrations.CreateModel(
            name="EducationInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_degree_name", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                (
                    "university_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("starting_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("gpa", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations_information",
                        to="seekers.seekerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "educations_information",
                "ordering": ["completion_date"],
            },
        ),
    ]
