# Generated by Django 4.1.2 on 2022-10-23 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_description",
                    models.TextField(blank=True, default="", max_length=256),
                ),
                ("established_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.TextField(blank=True, default="", max_length=256)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "company_location",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
