# Generated by Django 4.1.2 on 2022-10-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_alter_company_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
