# Generated by Django 4.1.2 on 2022-11-16 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment_posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikeComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like_comments",
                        to="comment_posts.commentpost",
                    ),
                ),
                ("like_user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
