# Generated by Django 4.1.2 on 2022-10-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_user_date_of_birth_user_gender_user_last_login_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(default="email", max_length=255),
        ),
    ]
