# Generated by Django 4.1.2 on 2022-11-24 14:42

import applicants.models.applicant
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("apply", "Apply"),
                            ("test", "Test"),
                            ("interview", "Interview"),
                            ("complete", "Complete"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="apply",
                        max_length=20,
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                ("status_do_test_date", models.DateTimeField(blank=True, null=True)),
                ("status_interview_date", models.DateTimeField(blank=True, null=True)),
                (
                    "interview_date_official",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=applicants.models.applicant.name_file,
                    ),
                ),
                ("information_added", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicants",
                        to="job.job",
                    ),
                ),
            ],
            options={
                "db_table": "applicants",
            },
        ),
        migrations.CreateModel(
            name="ApplicantTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("finish_date", models.DateTimeField(blank=True, null=True)),
                ("date_expired_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.FloatField(default=0)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "db_table": "applicant_test",
            },
        ),
    ]
