# Generated by Django 4.1.2 on 2022-11-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cv/"),
        ),
    ]
