# Generated by Django 4.1.2 on 2022-11-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_interview", models.DateTimeField(blank=True, null=True)),
                ("end_interview", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "applicant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicants.applicant",
                    ),
                ),
            ],
            options={
                "db_table": "applicant_interview",
            },
        ),
    ]
