# Generated by Django 4.1.2 on 2022-11-22 17:05

import applicants.models.applicant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_applicant_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="information_added",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=applicants.models.applicant.name_file
            ),
        ),
    ]
