# Generated by Django 4.1.2 on 2022-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0002_applicantinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantinterview",
            name="status",
            field=models.CharField(
                choices=[
                    ("set_schedule", "Set Schedule"),
                    ("schedule_interview", "Schedule Interview"),
                    ("cancel_interview", "Cancel Interview"),
                    ("complete", "Complete"),
                ],
                default="set_schedule",
                max_length=20,
            ),
        ),
    ]
