# Generated by Django 4.1.2 on 2022-11-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0003_applicantinterview_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantinterview",
            name="choice_set_schedule_interview",
            field=models.CharField(
                choices=[("automate", "Automate"), ("manual", "Manual")],
                default="automate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="applicantinterview",
            name="end_set_schedule_interview",
            field=models.DateField(blank=True, null=True),
        ),
    ]
