# Generated by Django 4.1.2 on 2022-12-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0006_alter_applicantinterview_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicantinterview",
            name="status",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("apply", "Apply"),
                    ("test", "Test"),
                    ("set_schedule", "Set Schedule"),
                    ("interview_pending", "Interview Pending"),
                    ("schedule_interview", "Schedule Interview"),
                    ("cancel_interview", "Cancel Interview"),
                    ("interview_complete", "Interview Complete"),
                    ("complete", "Complete"),
                    ("incomplete", "Incomplete"),
                ],
                default="apply",
                max_length=20,
            ),
        ),
    ]
