# Generated by Django 4.1.2 on 2022-12-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0007_remove_applicantinterview_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="is_send_email",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
