# Generated by Django 4.1.2 on 2022-12-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0008_applicant_is_send_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="link_gg_meet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
