# Generated by Django 4.1.2 on 2022-12-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applicants", "0009_applicant_link_gg_meet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="link_gg_meet",
            field=models.URLField(blank=True, null=True),
        ),
    ]
